#!/bin/tcsh -f
set path = (/usr/local/bin /usr/local/sbin /usr/bin /usr/sbin /bin /sbin /usr/local/games /usr/games)
set echo_style = none
set in = /tmp/rcon_in

set player = /tmp/player_io
set ip = /tmp/ip_io

auth:
  set auth = "`head -1 | tr -d '\r'`"

if ( { ( echo "$auth" | \
grep -qa \
'^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: .*\[/[0-9]*.[0-9]*.[0-9]*.[0-9]*:[0-9]*] logged in with entity id [0-9]* at (.*)$' ) } ) \
then
  echo "$auth" | sed -u 's/\[\/[0-9]*.[0-9]*.[0-9]*.[0-9]*:[0-9]*].*//;s/.*: //' > $player
  echo "$auth" | sed -u "s/.*\[\///;s/:.*//" > $ip
  if ( ! { ( grep -qwa "^`cat $player`" auth ) } && ! { ( grep -qwa "`cat $ip`"\$"" auth ) } ) then
    ( tr '\n' ' ' < $player ; cat $ip ) | tee -a auth
  else
    grep -Fqxa "`tr -d '\n' < $player` `cat $ip`" auth || \
    echo "/kick `cat $player` You may not use this username\!" | tee $in
  endif
endif
goto auth
