#!/bin/bash
in=rcon_in

while read -r cmds
do
  if echo "$cmds" | \
  grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !info$'
  then
    echo "/say $(uname -a)" | nc -U $in
  elif echo "$cmds" | \
  grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !date$'
  then
    echo "/say $(date)" | nc -U $in
  elif echo "$cmds" | \
  grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !script$' ||
  echo "$cmds" | \
  grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !license$' ||
  echo "$cmds" | \
  grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !source$'
  then
    echo "/say Minecraft Shell - A Unix shell script made by a Unix guru." | \
    nc -U $in
    echo "/say Minecraft Shell is released under the terms of the GNU AGPLv3 license." | \
    nc -U $in
    echo "/say You may ask an administrator for the modified source code of this program." | \
    nc -U $in
    echo "/say The original source code can be found at: https://github.com/Krush206/minecraft-shell" | \
    nc -U $in
  elif echo "$cmds" | \
  grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !guild'
  then
    player=$(echo "$cmds" | sed --posix -u 's/.*<//;s/>.*//')
    if echo "$cmds" | \
    grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !guild create [a-zA-Z0-9]\{2,10\}$'
    then
      guild=$(echo "$cmds" | sed --posix -u 's/^.*create //')
      if ! grep -qwa "^$guild" guilds
      then
        echo "$guild $player" >> guilds
        echo "/tellraw $player {\"text\":\"Guild created successfully!\",\"color\":\"green\"}" | \
        nc -U $in
      else
        echo "/tellraw $player {\"text\":\"This guild already exists in the database!\",\"color\":\"red\"}" | \
        nc -U $in
      fi
    elif echo "$cmds" | \
    grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !guild join [a-zA-Z0-9]\{2,10\}$'
    then
      guild=$(echo "$cmds" | sed --posix -u 's/^.*join //')
      if ! grep -qwa "$player" guilds
      then
        if grep -qwa "$guild" guilds
        then
          sed --posix -i "/$guild/ s/$/ $player/" guilds
          echo "/tellraw $player {\"text\":\"Joined $guild guild successfully!\",\"color\":\"green\"}" | \
          nc -U $in
        else
          echo "/tellraw $player {\"text\":\"This guild does not exist!\",\"color\":\"red\"}" | nc -U $in
        fi
      else
        echo "/tellraw $player {\"text\":\"You must first leave your current guild to join another!\",\"color\":\"red\"}" | \
        nc -U $in
      fi
    elif echo "$cmds" | \
    grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !guild disband$'
    then
      if grep -qwa "$player" guilds
      then
        if grep -qwa "^$(sed --posix -nu /$player/p guilds | awk --posix '{ print $1 }') $player" guilds
        then
          sed --posix -i "/$player/d" guilds
          echo "/tellraw $player {\"text\":\"You disbanded the guild!\",\"color\":\"yellow\"}" | \
          nc -U $in
        else
          echo "/tellraw $player {\"text\":\"You are not the owner of the guild!\",\"color\":\"red\"}" | \
          nc -U $in
        fi
      else
        echo "/tellraw $player {\"text\":\"You are not currently in a guild!\",\"color\":\"red\"}" | \
        nc -U $in
      fi
    elif echo "$cmds" | \
    grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !guild leave$'
    then
      if grep -qwa "$player" guilds
      then
        sed --posix -i "s/ $player//" guilds
        echo "/tellraw $player {\"text\":\"You left the guild!\",\"color\":\"yellow\"}" | \
        nc -U $in
      else
        echo "/tellraw $player {\"text\":\"You are not currently in a guild!\",\"color\":\"red\"}" | \
        nc -U $in
      fi
    else
      echo "/tellraw $player {\"text\":\"Usage: !guild <create|join|disband|leave>\",\"color\":\"red\"}" | \
      nc -U $in
    fi
  elif echo "$cmds" | \
  grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !warp'
  then
    player=$(echo "$cmds" | sed --posix -u 's/.*<//;s/>.*//')
    if grep -qwa "$player" ops.json
    then
      if echo "$cmds" | \
      grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !warp to [a-zA-Z0-9]\{1,16\}$'
      then
        warp=$(echo "$cmds" | sed --posix -u 's/.*!warp to //')
        if grep -qwa "$warp" warps
        then
          echo "/tp $player $(sed --posix -nu "s/$warp //p" warps)" | nc -U $in
        else
          echo "/tellraw $player {\"text\":\"This warp does not exist!\",\"color\":\"red\"}" | \
          nc -U $in
        fi
      elif echo "$cmds" | \
      grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !warp set [a-zA-Z0-9]\{1,16\}$'
      then
        warp=$(echo "$cmds" | sed --posix -u 's/.*!warp set //')
        if ! grep -qwa "$warp" warps
        then
          echo "/tp $player ~ ~ ~" | nc -U $in
          read -r position
          position=$(echo -n "$position" | sed --posix -u "s/.*$player to //;s/[,]//g")
          echo "$warp $position" >> warps
        else
          echo "/tellraw $player {\"text\":\"This warp already exists in the database!\",\"color\":\"red\"}" | \
          nc -U $in
        fi
      elif echo "$cmds" | \
      grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !warp unset [a-zA-Z0-9]\{1,16\}$'
      then
        warp=$(echo "$cmds" | sed --posix -u 's/.*!warp unset //')
        if grep -qwa "$warp" warps
        then
          sed --posix -i "/$warp [0-9]*/d" warps
          echo "/tellraw $player {\"text\":\"Warp $warp has been deleted!\",\"color\":\"yellow\"}" | \
          nc -U $in
        else
          echo "/tellraw $player {\"text\":\"This warp does not exist!\",\"color\":\"red\"}" | \
          nc -U $in
        fi
      elif echo "$cmds" | \
      grep -qa '^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: <.*> !warp list$'
      then
        echo "/tellraw $player \"$(awk --posix '{ printf "%s ",$1 }' warps)\"" | nc -U $in
      else
        echo "/tellraw $player {\"text\":\"Usage: !warp <set|list|unset|to>\",\"color\":\"red\"}" | \
        nc -U $in
      fi
    else
      echo "/tellraw $player {\"text\":\"You may not perform this command!\",\"color\":\"red\"}" | \
      nc -U $in
    fi
  fi
done
