#!/bin/tcsh -f
setenv in rcon_in

setenv player /tmp/player_io
setenv ip /tmp/ip_io

auth:
  setenv auth "$<"

if ( { ( echo "$auth" | \
grep -qa \
'^\[[0-9]*:[0-9]*:[0-9]*] \[Server thread/INFO]: .*\[/[0-9]*.[0-9]*.[0-9]*.[0-9]*:[0-9]*] logged in with entity id [0-9]* at (.*)$' ) } ) \
then
  echo "$auth" | sed -u 's/\[\/[0-9]*.[0-9]*.[0-9]*.[0-9]*:[0-9]*].*//;s/.*: //' > $player
  echo "$auth" | sed -u "s/.*\[\///;s/:.*//" > $ip
  if ( ! { ( grep -qwa "^`tee < $player`" auth ) } && ! { ( grep -qwa "`tee < $ip`"\$"" auth ) } ) then
    ( tr '\n' ' ' < $player ; tee < $ip ) >> auth
  else
    grep -Fqxa "`tr -d '\n' < $player` `tee < $ip`" auth ||
    echo "/kick `tee < $player` You may not use this username\!" > $in
  endif
endif
goto auth
