#!/bin/tcsh -f

if ( $1 == "" || $2 == "" || $3 == "" || \
{ ( echo "$1\n$2\n$3" | grep -qa '[^0-9.]' ) } ) \
eval "echo 'Usage: ./rcon_interactive <server ip> <logs port> <commands port>' ; \
exit 1"

set rcon_out=/tmp/rcon_out
mkfifo $rcon_out >& /dev/null

echo "Remote connection from `whoami`" | \
nc $1 $3 || exit 1
clear
while 1
  ( exec nc $1 $3 < $rcon_out & )
  glob 'input> '
  head -1 > $rcon_out
  ( exec head -5 $rcon_out & )
  nc $1 $2 > $rcon_out
end

