#!/bin/bash
in=rcon_in

while true
do
  echo "/say Message one." | nc -U $in
  echo "/say Message two." | nc -U $in
  echo "/say Message three." | nc -U $in
  sleep 30
  echo "/say Message four." | nc -U $in
  echo "/say Message five." | nc -U $in
  sleep 300
  echo "/say This server makes use of Minecraft Shell, or parts of it." | nc -U $in
  echo "/say Minecraft Shell is released under the terms of the GNU AGPLv3 license." | nc -U $in
  echo "/say You may ask an administrator for the modified source code of this program." | nc -U $in
  echo "/say The original source code can be found at: https://github.com/Krush206/minecraft-shell" | nc -U $in
  sleep 45
done
